---
# roles/pg_backup/tasks/main.yml

- name: Add PosgreSQL apt repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_lsb.codename}}-pgdg main' state=present
  register: add_postgresql_repo
  when: "'pg_backup' in group_names"

- name: Add PosgreSQL apt key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  when: "'pg_backup' in group_names"

- name: Update package list
  apt: update_cache=yes cache_valid_time=7200
  when: "'pg_backup' in group_names and add_postgresql_repo is changed"

- name: Install PostgreSQL server
  apt: name="postgresql-server-dev-{{ postgresql_version }}" state=present
  when: "'pg_backup' in group_names"

- name: Install PostgreSQL client
  apt: name="postgresql-{{ postgresql_version }}" state=present
  when: "'pg_backup' in group_names"

- import_tasks: backup.yml
  when: backup_postgres in ["plain", "dump"]

## chmod couchdb user to read and write to /opt/data/backups
- name: chmod couchdb user to read and write to /opt/data/backups
  shell: |
    chown postgres:postgres /opt/data/backups/postgresql
  become: yes
  tags:
    - cron
    - backups

- name: Install boto3 (1.10.0 for backup )
  become: yes
  pip:
    name:
      - boto3==1.10.0
    state: latest
    executable: pip
  become_user: postgres